version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: restaurant_dwh
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=Andrei
      - CLICKHOUSE_PASSWORD=****
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes: 
      - ./clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_logs:/var/log/clickhouse-server